### Get a cart by ID
POST http://localhost:8000/carts/get-cart
Content-Type: application/json

{
  "cartId": 1
}

### Create a new cart
POST http://localhost:8000/carts/manage-cart
Content-Type: application/json

{
  "userId": 11,
  "products": [
    { "id": 1, "quantity": 2 },
    { "id": 2, "quantity": 1 }
  ]
}

### Update an existing cart
POST http://localhost:8000/carts/manage-cart
Content-Type: application/json

{
  "cartId": 1,
  "userId": 5,
  "products": [
    { "id": 3, "quantity": 3 },
    { "id": 4, "quantity": 2 }
  ]
}
