### Get all products
GET http://localhost:3002/products
Accept: application/json

### Get a single product by ID
POST http://localhost:3002/products/single-product
Content-Type: application/json

{
  "id": 1
}
